server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/backend
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq
    port: 5672   
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie-service
